###############################################################################
# Jekyll
markdown: kramdown
port: 3000
safe: true
language: 'en'

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - vendor
  - .bundle

###############################################################################
# Site
url: https://bakhtiyar.js.org
baseurl: ""
title: Bakhtiyar Syed
description: >-
  Bakhtiyar Syed - Staff Software Engineer, Machine Learning at LinkedIn,
  based in Dublin, Ireland.

###############################################################################
# Details
author: Bakhtiyar Syed
role: Staff Software Engineer, Machine Learning
company: LinkedIn
location: Dublin, Ireland
avatar: baks-2026.png
email: bakhtiyar.hsyed@gmail.com

# Profiles
github: bakszero
linkedin: bakhtiyar-syed
google_scholar: slTchcMAAAAJ

###############################################################################
# Google Analytics (leave blank to disable)
google_analytics:
