###############################################################################
# Jekyll Configuration
highlighter: rouge
markdown: kramdown
permalink: /:title.html
#paginate: 5
port: 3000
safe: true
language: 'en-uk'
plugins: [jekyll-feed]

###############################################################################
# Page Personal Details
url: http://bakszero.github.io/
baseurl: /
author: Bakhtiyar Syed
title: Bakhtiyar Syed | Welcome to my homepage
description: Personal Landing Page
avatar: baks4.jpg

# Contacts
email: baksoverflow@gmail.com

# Upon Request for Phone, Skype, Hangouts, etc.
urequest: Upon request

# Social Usernames for Twitter, Github, Medium, Linkedin
username: bakszero

# Research Outputs
google_scholar: slTchcMAAAAJ
#orcid: 0000-0001-8728-9449

# Google Analytics
google_analytics: UA-47728743-1
